<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('plants')->insert([
            [
                'name_id' => 'Kelp',
                'name_en' => 'Kelp',
                'domain' => 'Eukaryota',
                'phylum' => 'Gyrista',
                'subphylum' => 'Ochrophytina',
                'class' => 'Phaeophyceae',
                'order' => 'Laminariales',
                'family' => 'Laminariaceae',
                'genus' => 'Laminaria',
                'species' => 'digitata',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Atlantik Utara',
                'ekologi' => 'Penyedia tempat berlindung dan makanan bagi berbagai organisme laut.',
                'description' => 'Kelp adalah sejenis rumput laut yang tumbuh di perairan laut dangkal. Kelp merupakan salah satu jenis ganggang coklat yang memiliki bentuk seperti tumbuhan. Kelp memiliki batang yang panjang dan daun yang lebar.',
            ],
            [
                'name_id' => 'Ganggang Hijau',
                'name_en' => 'Green Algae',
                'domain' => 'Eukaryota, Bacteria',
                'phylum' => 'Chlorophyta (for green algae)',
                'subphylum' => 'Chlorophytina',
                'class' => 'Chlorophyceae',
                'order' => '',
                'family' => 'Ulvaceae',
                'genus' => 'Ulva',
                'species' => 'lactuca',
                'habitat' => 'Perairan laut dangkal',
                'distribusi' => 'Seluruh dunia',
                'ekologi' => 'Dimanfaatkan sebagai bahan makanan dan sumber nutrisi bagi manusia dan hewan laut.',
                'description' => 'Ganggang hijau adalah sekelompok organisme fotosintetik yang tidak memiliki akar, batang, dan daun. Ganggang hijau dapat ditemukan di berbagai tempat, mulai dari air tawar, air laut, hingga daratan. Ganggang hijau merupakan organisme yang sangat penting bagi kehidupan di bumi.',
            ],
            [
                'name_id' => 'Rumput Laut Merah',
                'name_en' => 'Red Seaweed',
                'domain' => 'Eukaryota',
                'phylum' => 'Rhodophyta',
                'subphylum' => '',
                'class' => 'Florideophyceae',
                'order' => '',
                'family' => 'Laminariaceae',
                'genus' => 'Saccharina',
                'species' => 'japonica',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Laut Jepang dan sekitarnya',
                'ekologi' => 'Dimanfaatkan sebagai bahan makanan dan sumber nutrisi.',
                'description' => 'Rumput laut merah adalah sejenis alga merah yang tumbuh di perairan laut. Rumput laut merah memiliki beragam ukuran dan bentuk, dan sering kali memberikan warna merah yang indah pada lingkungan laut. Beberapa jenis rumput laut merah juga memiliki nilai ekonomis yang tinggi sebagai bahan makanan, kosmetik, dan obat-obatan.',
            ],
            [
                'name_id' => 'Caulerpa',
                'name_en' => 'Caulerpa',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Ulvophyceae',
                'order' => 'Bryopsidales',
                'family' => 'Phaeophyceae',
                'genus' => 'Fucus',
                'species' => 'vesiculosus',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Atlantik Utara',
                'ekologi' => 'Memberikan habitat bagi organisme laut kecil dan menjadi sumber makanan.',
                'description' => 'Caulerpa adalah genus rumput laut hijau yang tumbuh di perairan hangat di seluruh dunia. Rumput laut ini memiliki struktur yang menyerupai tanaman darat dengan batang, daun, dan akar palsu. Beberapa spesies Caulerpa juga dimanfaatkan sebagai bahan makanan dan sumber nutrisi.',
            ],
            [
                'name_id' => 'Sea Lettuce',
                'name_en' => 'Sea Lettuce',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Ulvophyceae',
                'order' => 'Ulvales',
                'family' => 'Chlorophyta',
                'genus' => 'Caulerpa',
                'species' => 'taxifolia',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Laut Tengah',
                'ekologi' => 'Bisa menjadi invasif di beberapa ekosistem laut.',
                'description' => 'Sea lettuce adalah sejenis rumput laut hijau yang sering ditemukan di perairan laut dangkal di seluruh dunia. Rumput laut ini memiliki struktur tipis dan daun yang mirip dengan selada. Sea lettuce sering dimanfaatkan sebagai bahan makanan dan juga memberikan nutrisi bagi kehidupan laut lainnya.',
            ],
            [
                'name_id' => 'Brown Algae',
                'name_en' => 'Brown Algae',
                'domain' => 'Eukaryota',
                'phylum' => 'Ochrophyta',
                'subphylum' => '',
                'class' => 'Phaeophyceae',
                'order' => '',
                'family' => 'Chlorophyta',
                'genus' => 'Ulva',
                'species' => 'intestinalis',
                'habitat' => 'Perairan laut dangkal',
                'distribusi' => 'Seluruh dunia',
                'ekologi' => 'Membentuk padang lamun dan memberikan habitat bagi berbagai organisme laut.',
                'description' => 'Brown algae adalah sekelompok ganggang coklat yang tumbuh di perairan laut di seluruh dunia. Ganggang coklat ini memiliki beragam ukuran, mulai dari yang mikroskopis hingga yang besar seperti kelp. Beberapa jenis brown algae juga dimanfaatkan sebagai bahan makanan dan bahan tambahan dalam industri kosmetik dan farmasi.',
            ],
            [
                'name_id' => 'Ulva',
                'name_en' => 'Ulva',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Ulvophyceae',
                'order' => 'Ulvales',
                'family' => 'Rhodophyta',
                'genus' => 'Porphyra',
                'species' => 'umbilicalis',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Lautan Hangat di Seluruh Dunia',
                'ekologi' => 'Digunakan dalam berbagai hidangan kuliner Asia, seperti sushi.',
                'description' => 'Ulva, juga dikenal sebagai sea lettuce, adalah genus rumput laut hijau yang tumbuh di perairan laut dangkal di seluruh dunia. Ulva memiliki struktur tipis dan daun yang mirip dengan selada. Beberapa spesies Ulva dimanfaatkan sebagai bahan makanan dan sumber nutrisi bagi manusia dan hewan laut.',
            ],
            [
                'name_id' => 'Gracilaria',
                'name_en' => 'Gracilaria',
                'domain' => 'Eukaryota',
                'phylum' => 'Rhodophyta',
                'subphylum' => '',
                'class' => 'Florideophyceae',
                'order' => 'Gracilariales',
                'family' => 'Chlorophyta',
                'genus' => 'Codium',
                'species' => 'fragile',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Atlantik Utara',
                'ekologi' => 'Membentuk padang lamun dan memberikan habitat bagi berbagai organisme laut.',
                'description' => 'Gracilaria adalah genus rumput laut merah yang tumbuh di perairan laut hangat di seluruh dunia. Rumput laut ini memiliki struktur yang berbeda-beda, mulai dari yang berbentuk ranting hingga yang berbentuk daun. Beberapa spesies Gracilaria dimanfaatkan sebagai bahan makanan, bahan tambahan dalam industri makanan, dan juga sebagai sumber agar-agar.',
            ],
            [
                'name_id' => 'Hijau Laut',
                'name_en' => 'Seaweed',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Ulvophyceae',
                'order' => '',
                'family' => 'Phaeophyceae',
                'genus' => 'Sargassum',
                'species' => 'natans',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Samudra Atlantik',
                'ekologi' => 'Memberikan habitat bagi berbagai organisme laut dan bisa membentuk padang rumput laut yang luas.',
                'description' => 'Hijau laut adalah sekelompok alga hijau yang tumbuh di perairan laut di seluruh dunia. Alga hijau ini memiliki beragam bentuk dan ukuran, mulai dari yang mikroskopis hingga yang besar. Hijau laut memiliki peran penting dalam ekosistem laut, menyediakan makanan dan tempat berlindung bagi berbagai organisme laut. Beberapa jenis hijau laut juga dimanfaatkan sebagai bahan makanan dan bahan tambahan dalam industri makanan dan kosmetik.',
            ],
            [
                'name_id' => 'Mermaid\'s Fan',
                'name_en' => 'Mermaid\'s Fan',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Bryopsidophyceae',
                'order' => '',
                'family' => 'Chlorophyta',
                'genus' => 'Halimeda',
                'species' => 'macroloba',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Samudra Pasifik',
                'ekologi' => 'Mempunyai peranan penting dalam pembentukan sedimen karbonat dan menyediakan habitat bagi berbagai organisme laut.',
                'description' => 'Mermaid\'s fan, juga dikenal sebagai Udotea, adalah jenis rumput laut hijau yang memiliki bentuk seperti kipas. Mermaid\'s fan tumbuh di perairan hangat dan dangkal di berbagai wilayah tropis dan subtropis di seluruh dunia. Rumput laut ini memiliki peranan penting dalam menjaga ekosistem laut yang seimbang.',
            ],
            [
                'name_id' => 'Irish Moss',
                'name_en' => 'Irish Moss',
                'domain' => 'Eukaryota',
                'phylum' => 'Rhodophyta',
                'subphylum' => '',
                'class' => 'Florideophyceae',
                'order' => 'Gigartinales',
                'family' => 'Rhodophyta',
                'genus' => 'Gracilaria',
                'species' => 'verrucosa',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Samudra Hindia',
                'ekologi' => 'Digunakan dalam industri makanan, farmasi, dan kosmetik.',
                'description' => 'Irish moss, juga dikenal sebagai Chondrus crispus, adalah jenis rumput laut merah yang tumbuh di perairan laut dingin di Atlantik Utara. Irish moss memiliki tekstur yang kenyal dan sering dimanfaatkan dalam industri makanan dan kosmetik sebagai bahan pengental dan pelembut.',
            ],
            [
                'name_id' => 'Rockweed',
                'name_en' => 'Rockweed',
                'domain' => 'Eukaryota',
                'phylum' => 'Ochrophyta',
                'subphylum' => '',
                'class' => 'Phaeophyceae',
                'order' => 'Fucales',
                'family' => 'Phaeophyceae',
                'genus' => 'Ecklonia',
                'species' => 'cava',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Laut Jepang',
                'ekologi' => 'Memberikan habitat bagi berbagai organisme laut dan menjadi sumber makanan.',
                'description' => 'Rockweed adalah sejenis rumput laut coklat yang tumbuh menempel pada batu dan bebatuan di perairan laut. Rockweed memiliki peranan penting dalam ekosistem laut, menyediakan tempat berlindung dan makanan bagi berbagai organisme laut. Beberapa spesies rockweed juga dimanfaatkan sebagai bahan pupuk dan pakan ternak.',
            ],
            [
                'name_id' => 'Sea Grapes',
                'name_en' => 'Sea Grapes',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Ulvophyceae',
                'order' => 'Ulvales',
                'family' => 'Chlorophyta',
                'genus' => 'Enteromorpha',
                'species' => 'compressa',
                'habitat' => 'Perairan laut dangkal',
                'distribusi' => 'Laut Baltik',
                'ekologi' => 'Membentuk padang lamun dan menjadi sumber makanan bagi hewan laut.',
                'description' => 'Sea grapes adalah jenis rumput laut hijau yang memiliki bentuk dan tekstur yang mirip dengan anggur laut. Sea grapes tumbuh di perairan laut hangat di berbagai wilayah tropis dan subtropis di seluruh dunia. Beberapa spesies sea grapes juga dimanfaatkan sebagai bahan makanan dan sumber nutrisi bagi manusia.',
            ],
            [
                'name_id' => 'Red Algae',
                'name_en' => 'Red Algae',
                'domain' => 'Eukaryota',
                'phylum' => 'Rhodophyta',
                'subphylum' => '',
                'class' => 'Florideophyceae',
                'order' => '',
                'family' => 'Rhodophyta',
                'genus' => 'Chondrus',
                'species' => 'crispus',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Atlantik Utara',
                'ekologi' => 'Digunakan dalam industri makanan dan kosmetik sebagai bahan pengental dan pelembut.',
                'description' => 'Red algae adalah sekelompok ganggang merah yang tumbuh di perairan laut di seluruh dunia. Ganggang merah ini memiliki beragam ukuran dan bentuk, mulai dari yang mikroskopis hingga yang besar. Beberapa jenis red algae juga dimanfaatkan sebagai bahan makanan, bahan tambahan dalam industri makanan dan kosmetik, serta sebagai sumber agar-agar.',
            ],
            [
                'name_id' => 'Codium',
                'name_en' => 'Codium',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Bryopsidophyceae',
                'order' => 'Bryopsidales',
                'family' => 'Phaeophyceae',
                'genus' => 'Fucus',
                'species' => 'serratus',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Laut Baltik',
                'ekologi' => 'Memberikan habitat bagi organisme laut kecil dan menjadi sumber makanan.',
                'description' => 'Codium adalah genus rumput laut hijau yang tumbuh di perairan laut di seluruh dunia. Rumput laut ini memiliki bentuk seperti bola atau ranting dan tumbuh di lingkungan laut yang berbatu. Codium memiliki peranan penting dalam menjaga ekosistem laut yang seimbang dan juga dimanfaatkan sebagai bahan makanan.',
            ],
            [
                'name_id' => 'Halimeda',
                'name_en' => 'Halimeda',
                'domain' => 'Eukaryota',
                'phylum' => 'Chlorophyta',
                'subphylum' => '',
                'class' => 'Bryopsidophyceae',
                'order' => 'Bryopsidales',
                'family' => 'Chlorophyta',
                'genus' => 'Caulerpa',
                'species' => 'peltata',
                'habitat' => 'Perairan laut tropis',
                'distribusi' => 'Laut Karibia',
                'ekologi' => 'Bisa menjadi invasif di beberapa ekosistem laut dan mempengaruhi ekosistem karang.',
                'description' => 'Halimeda adalah genus rumput laut hijau yang tumbuh di perairan laut hangat di seluruh dunia. Rumput laut ini memiliki struktur yang menyerupai dedaunan dan sering ditemukan di lingkungan karang. Halimeda memiliki peranan penting dalam ekosistem laut dan juga dimanfaatkan sebagai bahan makanan dan pupuk.',
            ],
            [
                'name_id' => 'Oarweed',
                'name_en' => 'Oarweed',
                'domain' => 'Eukaryota',
                'phylum' => 'Ochrophyta',
                'subphylum' => '',
                'class' => 'Phaeophyceae',
                'order' => 'Laminariales',
                'family' => 'Rhodophyta',
                'genus' => 'Palmaria',
                'species' => 'palmata',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Atlantik Utara',
                'ekologi' => 'Digunakan dalam industri makanan dan kosmetik sebagai bahan pewarna alami.',
                'description' => 'Oarweed adalah jenis rumput laut coklat yang tumbuh di perairan laut di seluruh dunia. Rumput laut ini memiliki struktur yang panjang dan menyerupai dayung, dan sering ditemukan di perairan laut yang berarus deras. Oarweed memiliki peranan penting dalam menyediakan tempat berlindung dan makanan bagi berbagai organisme laut.',
            ],
            [
                'name_id' => 'Bladderwrack',
                'name_en' => 'Bladderwrack',
                'domain' => 'Eukaryota',
                'phylum' => 'Ochrophyta',
                'subphylum' => '',
                'class' => 'Phaeophyceae',
                'order' => 'Fucales',
                'family' => 'Chlorophyta',
                'genus' => 'Cladophora',
                'species' => 'rupestris',
                'habitat' => 'Perairan laut dangkal',
                'distribusi' => 'Seluruh dunia',
                'ekologi' => 'Membentuk padang lamun dan menyediakan habitat bagi berbagai organisme laut.',
                'description' => 'Bladderwrack adalah jenis rumput laut coklat yang tumbuh di perairan laut di berbagai wilayah dunia, terutama di perairan Atlantik Utara. Rumput laut ini memiliki gelembung-gelembung udara di sepanjang batangnya yang membantu menjaga kestabilan saat berada di permukaan air. Bladderwrack memiliki peran penting dalam ekosistem laut dan juga dimanfaatkan sebagai sumber nutrisi dan bahan kosmetik.',
            ],
            [
                'name_id' => 'Sea Whip',
                'name_en' => 'Sea Whip',
                'domain' => 'Eukaryota',
                'phylum' => 'Cnidaria',
                'subphylum' => '',
                'class' => 'Anthozoa',
                'order' => 'Gorgonacea',
                'family' => 'Phaeophyceae',
                'genus' => 'Undaria',
                'species' => 'pinnatifida',
                'habitat' => 'Perairan laut dingin',
                'distribusi' => 'Laut Jepang',
                'ekologi' => 'Dimanfaatkan dalam masakan tradisional Jepang dan telah menjadi spesies invasif di beberapa wilayah.',
                'description' => 'Sea whip adalah jenis karang lunak yang memiliki bentuk menyerupai cambuk laut. Sea whip tumbuh di perairan laut hangat di berbagai wilayah dunia dan biasanya hidup di dasar laut yang berbatu. Sea whip memiliki peranan penting dalam ekosistem laut sebagai tempat tinggal dan tempat berlindung bagi berbagai organisme laut.',
            ],
            [
                'name_id' => 'Laminaria',
                'name_en' => 'Laminaria',
                'domain' => 'Eukaryota',
                'phylum' => 'Ochrophyta',
                'subphylum' => '',
                'class' => 'Phaeophyceae',
                'order' => 'Laminariales',
                'family' => 'Rhodophyta',
                'genus' => 'Gelidium',
                'species' => 'amansii',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Samudra Pasifik',
                'ekologi' => 'Digunakan dalam industri makanan, farmasi, dan kosmetik.',
                'description' => 'Laminaria adalah genus rumput laut coklat yang tumbuh di perairan laut di berbagai wilayah dunia, terutama di perairan laut yang beriklim dingin. Rumput laut ini memiliki peranan penting dalam ekosistem laut sebagai penyedia makanan dan tempat berlindung bagi berbagai organisme laut.',
            ],
            [
                'name_id' => 'Seagrass',
                'name_en' => 'Seagrass',
                'domain' => 'Eukaryota',
                'phylum' => 'Anthophyta',
                'subphylum' => '',
                'class' => 'Liliopsida',
                'order' => '',
                'family' => 'Rhodophyta',
                'genus' => 'Porphyra',
                'species' => 'umbilicalis',
                'habitat' => 'Perairan laut dangkal',
                'distribusi' => 'Seluruh dunia',
                'ekologi' => 'Memberikan habitat bagi berbagai organisme laut dan membantu menjaga kestabilan ekosistem laut.',
                'description' => 'Seagrass, atau rumput laut, adalah jenis tumbuhan yang tumbuh di perairan laut dangkal di seluruh dunia. Seagrass memiliki akar dan batang yang menjalar di dasar laut dan sering membentuk padang lamun. Seagrass memiliki peran penting dalam ekosistem laut, menyediakan tempat berlindung dan makanan bagi berbagai organisme laut.',
            ],
            [
                'name_id' => 'Sargassum',
                'name_en' => 'Sargassum',
                'domain' => 'Eukaryota',
                'phylum' => 'Ochrophyta',
                'subphylum' => '',
                'class' => 'Phaeophyceae',
                'order' => 'Fucales',
                'family' => 'Rhodophyta',
                'genus' => 'Chondrus',
                'species' => 'crispus',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Samudra Atlantik',
                'ekologi' => 'Memberikan habitat bagi berbagai organisme laut dan bisa membentuk padang rumput laut yang luas.',
                'description' => 'Sargassum adalah genus rumput laut coklat yang tumbuh di perairan laut di seluruh dunia, terutama di perairan tropis dan subtropis. Rumput laut ini sering membentuk padang rumput laut yang luas di lautan terbuka. Sargassum memiliki peranan penting dalam ekosistem laut sebagai tempat tinggal dan tempat berkembang biak bagi berbagai organisme laut.',
            ],
            [
                'name_id' => 'Coralline Algae',
                'name_en' => 'Coralline Algae',
                'domain' => 'Eukaryota',
                'phylum' => 'Rhodophyta',
                'subphylum' => '',
                'class' => 'Florideophyceae',
                'order' => '',
                'family' => 'Rhodophyta',
                'genus' => 'Corallina',
                'species' => 'officinalis',
                'habitat' => 'Perairan laut hangat',
                'distribusi' => 'Laut Tengah',
                'ekologi' => 'Mempunyai peranan penting dalam pembentukan terumbu karang dan menjaga kestabilan ekosistem laut.',
                'description' => 'Coralline algae adalah jenis alga merah yang tumbuh di perairan laut di seluruh dunia. Alga merah ini memiliki kalsium karbonat pada dinding selnya yang membuatnya keras seperti batu. Coralline algae memiliki peran penting dalam pembentukan terumbu karang dan menjaga kestabilan ekosistem laut.',
            ],
            [
                'name_id' => 'Turtle Grass',
                'name_en' => 'Turtle Grass',
                'domain' => 'Eukaryota',
                'phylum' => 'Anthophyta',
                'subphylum' => '',
                'class' => 'Liliopsida',
                'order' => '',
                'family' => 'Rhodophyta',
                'genus' => 'Porphyra',
                'species' => 'umbilicalis',
                'habitat' => 'Perairan laut dangkal',
                'distribusi' => 'Seluruh dunia',
                'ekologi' => 'Memberikan habitat bagi berbagai organisme laut dan membantu menjaga kestabilan ekosistem laut.',
                'description' => 'Turtle grass, atau rumput penyu, adalah jenis rumput laut yang tumbuh di perairan laut dangkal di berbagai wilayah tropis dan subtropis di seluruh dunia. Rumput laut ini memiliki daun yang panjang dan lebar serta akar yang kuat. Turtle grass memiliki peran penting dalam ekosistem laut sebagai penyedia makanan dan tempat berlindung bagi berbagai organisme laut.',
            ],
        ]);
    }
}
